name: patching

# Controls when the workflow will run
permissions:
  id-token: write
  contents: read
on:
 # workflow_dispatch: 
  push:
    branches:
      - feature-3
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  patching:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::793421532190:role/github-patching
          aws-region: "us-east-1"
          role-session-name: ${{ github.run_id }}
          role-duration-seconds: "900"
          # mask-aws-account-id: "true"
      - name: Verify Initial OIDC Identity
        run: |
          echo "=== Initial OIDC Identity (Verified) ==="
          aws sts get-caller-identity

